server:
  port: 6001

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.3.145:8848
    sentinel:
      transport:
        dashboard: 172.16.3.145:8858
        client-ip: 172.16.9.53

feign:
  sentinel:
    enabled: true